version: 2.1

jobs:
  job:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: PR ready for review
          command: echo "PR ready for review"



     

workflows:
  ready-for-review-workflow:
    jobs:
      - job
